# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mojito"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Max Trense"]
  s.date = "2012-11-09"
  s.description = "A simple yet powerful webframework largely inspired by Rum and Cuba"
  s.email = "dev@trense.info"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    "LICENSE.txt",
    "VERSION",
    "lib/mojito.rb",
    "lib/mojito/base.rb",
    "lib/mojito/controllers.rb",
    "lib/mojito/controllers/entities.rb",
    "lib/mojito/controllers/method.rb",
    "lib/mojito/controllers/runtime.rb",
    "lib/mojito/controllers/runtime/environment.rb",
    "lib/mojito/controllers/runtime/methods.rb",
    "lib/mojito/controllers/runtime/path.rb",
    "lib/mojito/controllers/runtime/session.rb",
    "lib/mojito/controllers/runtime/url_scheme.rb",
    "lib/mojito/controllers/runtime/virtual_host.rb",
    "lib/mojito/controllers/sinatra.rb",
    "lib/mojito/helpers.rb",
    "lib/mojito/helpers/escape.rb",
    "lib/mojito/helpers/exception_handling.rb",
    "lib/mojito/helpers/shortcuts.rb",
    "lib/mojito/rendering.rb",
    "lib/mojito/rendering/cache.rb",
    "lib/mojito/rendering/content.rb",
    "lib/mojito/rendering/content_types.rb",
    "lib/mojito/rendering/delegation.rb",
    "lib/mojito/rendering/file.rb",
    "lib/mojito/rendering/markup.rb",
    "lib/mojito/rendering/status_codes.rb",
    "lib/mojito/rendering/templates.rb",
    "lib/mojito/request_extensions.rb",
    "lib/mojito/utils/rspec.rb",
    "lib/mojito/utils/status_codes.rb",
    "spec/mojito/base_spec.rb",
    "spec/mojito/controllers/method_spec.rb",
    "spec/mojito/controllers/runtime/methods_spec.rb",
    "spec/mojito/controllers/runtime/path_spec.rb",
    "spec/mojito/controllers/runtime/session_spec.rb",
    "spec/mojito/controllers/runtime/url_scheme_spec.rb",
    "spec/mojito/controllers/runtime/virtual_host_spec.rb",
    "spec/mojito/helpers_spec.rb",
    "spec/mojito/rendering/content_spec.rb",
    "spec/mojito/rendering/delegation_spec.rb",
    "spec/mojito/rendering/file_spec.rb",
    "spec/mojito/rendering/status_codes_spec.rb",
    "spec/mojito/rendering/templates_spec.rb",
    "spec/mojito/rendering_spec.rb",
    "spec/mojito/request_extensions_spec.rb",
    "spec/mojito_spec.rb"
  ]
  s.homepage = "http://github.com/mtrense/mojito"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.0")
  s.rubygems_version = "1.8.24"
  s.summary = "A simple yet powerful webframework largely inspired by Rum and Cuba"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, ["~> 1.4.0"])
      s.add_runtime_dependency(%q<mime-types>, ["~> 1.18"])
      s.add_runtime_dependency(%q<tilt>, ["~> 1.3.3"])
      s.add_runtime_dependency(%q<extlib>, ["~> 0.9.15"])
      s.add_runtime_dependency(%q<json_builder>, ["~> 3.1.7"])
      s.add_runtime_dependency(%q<where-am-i>, ["~> 1.0.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rack>, ["~> 1.4.0"])
      s.add_dependency(%q<mime-types>, ["~> 1.18"])
      s.add_dependency(%q<tilt>, ["~> 1.3.3"])
      s.add_dependency(%q<extlib>, ["~> 0.9.15"])
      s.add_dependency(%q<json_builder>, ["~> 3.1.7"])
      s.add_dependency(%q<where-am-i>, ["~> 1.0.0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rack>, ["~> 1.4.0"])
    s.add_dependency(%q<mime-types>, ["~> 1.18"])
    s.add_dependency(%q<tilt>, ["~> 1.3.3"])
    s.add_dependency(%q<extlib>, ["~> 0.9.15"])
    s.add_dependency(%q<json_builder>, ["~> 3.1.7"])
    s.add_dependency(%q<where-am-i>, ["~> 1.0.0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

