# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mojito"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Max Trense"]
  s.date = "2012-05-14"
  s.description = "A simple yet powerful webframework largely inspired by Rum and Cuba"
  s.email = "dev@trense.info"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    "LICENSE.txt",
    "VERSION",
    "lib/mojito.rb",
    "lib/mojito/helpers.rb",
    "lib/mojito/helpers/exception_handling.rb",
    "lib/mojito/matchers.rb",
    "lib/mojito/matchers/methods.rb",
    "lib/mojito/matchers/path.rb",
    "lib/mojito/matchers/virtual_host.rb",
    "lib/mojito/rendering.rb",
    "lib/mojito/rendering/content.rb",
    "lib/mojito/rendering/content_types.rb",
    "lib/mojito/rendering/delegation.rb",
    "lib/mojito/rendering/status_codes.rb",
    "lib/mojito/utils/status_codes.rb",
    "spec/mojito/matchers_spec.rb",
    "spec/mojito/rendering_spec.rb",
    "spec/mojito_spec.rb"
  ]
  s.homepage = "http://github.com/mtrense/mojito"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "A simple yet powerful webframework largely inspired by Rum and Cuba"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, ["~> 1.4.0"])
      s.add_runtime_dependency(%q<mime-types>, ["~> 1.18"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rack>, ["~> 1.4.0"])
      s.add_dependency(%q<mime-types>, ["~> 1.18"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rack>, ["~> 1.4.0"])
    s.add_dependency(%q<mime-types>, ["~> 1.18"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

